dist: xenial
language: java
jdk: openjdk11
addons:
  apt:
    packages:
      - pv
env:
  - MAVEN_OPTS="-Xmx4g"

script:

  - echo test > test.txt

deploy:
  provider: releases
  api_key:
    secure: "gAhzkjUix77ssnT1AmCjr9/rkpixMapITVF07poXaupNyySoWxv8EMQoI7FCw7kkVcjgvRpZny4juFKl2x5F/7m0Lg2V+6QmBzK5/P+ZLwCCjbldjomdquIDhRoAUbYIsFfYXODlz8Dv+XzcbienAYQHb4+OeKXBbvo22VCfGzLHSswWpQxID5K6c361dPBSv5weB5osUnnLnLq7fJbmemojoJQr1E9bSY+5hGG7tCcQh2IudHo/EHSC/pBXCijeIa6FochkRS5owVt+hjyw6ZuGFRW1ozqlB7P82LSt/vh+z2X+4rDFvIE0r/dDJg1PuwmjFK2gQZk+Cmrts5lIy54EUoWrpYL4zwWttCTdllgO0MMlBBJSuvglrnNbNKt2l/nB7L5mCJm+VlcL2HqGSPpbKrd1cL8jwV69XBvUYsPcsQj7dDZxjKPUrq1QZrKza7tHCoZArq7KwhpCdRWmzmqeHaVLfN6169uFzqL2wr9BtYNjcEd0wnnj7TvkQhCtzZBdbzRvxWyzJSjta1q4qshLGkf3OsBTi+H65bd2okR4sN5CcAVnE/PzLOy25d6ZYsQb0d8T8rIdBLMTRi25CBL7goVQTUR3j3bWf+GbwVyfAgjsIHo2RLeJTmApsWbRf6MAi/MiW/mv1qf566chTYHJdLCQQZz12BLb0tPaRcA="
  file: "test.txt"
  skip_cleanup: true
  overwrite: true
