dist: xenial
language: java
jdk: openjdk11
addons:
  apt:
    packages:
      - pv
env:
  - MAVEN_OPTS="-Xmx4g"

install:

  # Download the latest version of allCountries.zip gazetteer file from GeoNames.org
  - curl -O http://download.geonames.org/export/dump/allCountries.zip
  - unzip allCountries.zip
  - rm allCountries.zip
  - mv allCountries.txt CLAVIN/

  # Build CLAVIN
  - cd CLAVIN/
  - mvn compile
  - cd ../  

script:

  # Create the Lucene index
  - cd CLAVIN/
  - mvn exec:java -Dexec.mainClass="com.bericotech.clavin.index.IndexDirectoryBuilder"
  - cd ../

after_success:

  # Compress index directory
  - cd CLAVIN/
  - tar -cf ../IndexDirectory.tar IndexDirectory/
  - cd ../
  - pv IndexDirectory.tar | gzip -v9 > IndexDirectory.tar.gz

deploy:
  provider: releases
  api_key:
    secure: LDp1Ejzpeq5CN4WH2rnABljrx+j7hFxvKLAKFIbXwXBHRkswB73AZiWXwntyvJfMUxLDChzyqLU4qdI/BjCRmrVeqy53O/UVqiv/thO6VSdsl1q9YE3ufT54rf1ewopFhiH7B4rXK0hDIi/hRFzuj2C+gBR3aXolMS3az/Y6Kf20wtvMiYCCSx1nSj7oVaCdaz7tRnn2x6ceZAePcjd2JoZA+3KktSXMiTnvj9aOjsHITCNp499hg6ti9Em248/rnEoWhMEHfCAoavAfreFY8ov8ko4aSfhHCZXmwd2V/ZHJa5iVvg4wPQ3W+sFgz2I0seks89HDyT8fMJa0I23ItKggon+frFhy7K2Pv4pA7n3euuJGjb1jhUw4DdgR24bh8PqPWkKrNzHKYd5y7u8WifPSv9tRYWvF/TBpSxbgIc+bPLZTlGXdRjyFmlUkTskMHi8qz0NKhhZ1effxXNujLk6BPH8ALHNmgMWIFqRXNHKQYZkcECXzPQbR9pkqxNSb7ryZ97KWFV/zkObdPwgZgcKRupe1Qhcg9lYIs9eR+SENJonhRWD6KeE+a984NChDZ0RGsRn/04u+34kqQ04jkXN3nXD+xOSt/Ec4WPgayafeIH+H0WnhJC1SIf2wpKiit3DZXs9+tDCVYVC/3t4p2qh72VSaU2mLtIIFSIXhoCo=
  file: "IndexDirectory.tar.gz"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
